---
- name: Install  server
  hosts: g1
  become: yes

  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present
      when: ansible_distribution = "Amazon"

    - name: Start HTTPD
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution = "Amazon"

    - name: Enable HTTPD
      service:
        name: httpd
        enabled: yes
      when: ansible_distribution = "Amazon"

    - name: Install Apache
      apt:
        name: apache2
        state: present
      when: ansible_distribution = "Ubuntu"

    - name: Start apache2
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Enable apache2
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution = "Ubuntu"
...