---
    - name: Install and start HTTPD on Amazon Linux
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon" or ansible_distribution == "CentOs"

    - name: Ensure HTTPD is running and enabled on Amazon Linux
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Amazon" or ansible_distribution == "CentOs"

    - name: Update apt cache on Debian-based systems
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install and start Apache on Debian-based systems
      package:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Apache is running and enabled on Debian-based systems
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"
...